<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
		<PackageReference Include="TinyAppEngine" Version="1.0.58" />
		<PackageReference Include="TinyAppEngine.EFCore" Version="1.0.24" />
		<PackageReference Include="TinyAppEngine.Tools" Version="1.0.129" />
		<PackageReference Include="TinyAppEngine.Validations" Version="1.0.13" />
	</ItemGroup>

</Project>
