// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OperazioniAvvio.DataAccessLayer;

#nullable disable

namespace OperazioniAvvio.DataAccessLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260601160329_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OperazioniAvvio.DataAccessLayer.Entities.Festa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataFine")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_Feste");

                    b.ToTable("Feste", (string)null);
                });

            modelBuilder.Entity("OperazioniAvvio.DataAccessLayer.Entities.Impostazione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("GestioneCategorie")
                        .HasColumnType("bit");

                    b.Property<bool>("GestioneCoperti")
                        .HasColumnType("bit");

                    b.Property<bool>("GestioneMenu")
                        .HasColumnType("bit");

                    b.Property<int>("IdFesta")
                        .HasColumnType("int");

                    b.Property<bool>("StampaCarta")
                        .HasColumnType("bit");

                    b.Property<bool>("StampaLogo")
                        .HasColumnType("bit");

                    b.Property<bool>("StampaRicevuta")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdFesta")
                        .IsUnique();

                    b.ToTable("Impostazioni");
                });

            modelBuilder.Entity("OperazioniAvvio.DataAccessLayer.Entities.Intestazione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Edizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdFesta")
                        .HasColumnType("int");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Luogo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdFesta")
                        .IsUnique();

                    b.ToTable("Intestazioni");
                });

            modelBuilder.Entity("OperazioniAvvio.DataAccessLayer.Entities.Impostazione", b =>
                {
                    b.HasOne("OperazioniAvvio.DataAccessLayer.Entities.Festa", "Festa")
                        .WithOne("Impostazione")
                        .HasForeignKey("OperazioniAvvio.DataAccessLayer.Entities.Impostazione", "IdFesta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Festa");
                });

            modelBuilder.Entity("OperazioniAvvio.DataAccessLayer.Entities.Intestazione", b =>
                {
                    b.HasOne("OperazioniAvvio.DataAccessLayer.Entities.Festa", "Festa")
                        .WithOne("Intestazione")
                        .HasForeignKey("OperazioniAvvio.DataAccessLayer.Entities.Intestazione", "IdFesta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Festa");
                });

            modelBuilder.Entity("OperazioniAvvio.DataAccessLayer.Entities.Festa", b =>
                {
                    b.Navigation("Impostazione")
                        .IsRequired();

                    b.Navigation("Intestazione")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
